Description: |
  This template enables you to create the following resources.
  - A Route 53 Hosted zone.
  
# ------------------------------------------------------------
# Parameters/Mappings/Conditions section
# ------------------------------------------------------------
Parameters:
  EnvName:
    Description: Please select the environment you want to create. Besides, its name will be prefixed to all resources' name.
    Type: String
    AllowedValues:
      - dev1
      - dev2
      - prd
  AppServiceName:
    Description: Please enter the service name will be provided to the customer.
    Type: String
    Default: YourApp

  RevisionNumber:
    Description: The revision number of this template consists of 3 parts.
    Type: String
    Default: 0.4.0

  Route53CreatingMode:
    Description: |
      "CreateNewIndependentHostedZone" creates a new individual Route53 hosted zone.
      "CreateNewDependentSubDomainHostedZone" creates a new Route53 hosted zone as a sub domain of your existing Route53 hosted zone within this AWS account.
      Please ensure that you already created a parent Route53 hosted zone within this AWS account. Because this option will add a Route53 NS record which points to the sub domain zone to the parent zone.
      "DependOnExistingHostedZone" never creates Route53 hosted zone. However if you specify this parameter, subsequent CloudFormation templates can add arbitrary CNAME/ALIAS records in order for clients to point their endpoint with stable name.
    Type: String
    Default: CreateNewIndependentHostedZone
    AllowedValues:
      - CreateNewIndependentHostedZone
      - CreateNewDependentSubDomainHostedZone
      - DependOnExistingHostedZone

  # Parameters for the "CreateNewIndependentHostedZone" option.
  Route53NewHostedZoneName:
    Description: |
      If you specify the parameter "Route53CreatingMode" "CreateNewIndependentHostedZone", please specify the domain name you want to create.
      Whenever this parameter will be ignored except in that case.
    Type: String
    Default: your-app-example.com.

  # Parameters for the "CreateNewDependentSubDomainHostedZone" option.
  Route53ParentHostedZoneId:
    Description: |
      When you specify the parameters "Route53CreatingMode" "CreateNewDependentSubDomainHostedZone", you must specify this parameter properly.
      Whenever this parameter will be ignored except in that case.
    Type: AWS::Route53::HostedZone::Id

  Route53ParentHostedZoneName:
    Description: |
      If you specify the parameter "Route53CreatingMode" "CreateNewDependentSubDomainHostedZone", please specify the domain name of the parent hosted zone.
      The created domain name by this CFn template would be ${EnvName}.${Route53ParentHostedZoneName}.
    Type: String
    Default: your-app-example.com.

  # Parameters for the "DependOnExistingHostedZone" option.
  Route53DependentHostedZoneId:
    Description: |
      When you specify the parameters "Route53CreatingMode" "DependOnExistingHostedZone", you must specify this parameter properly.
      Whenever this parameter will be ignored except in that case.
    Type: AWS::Route53::HostedZone::Id

  Route53DependentHostedZoneName:
    Description:
      Please specify the domain name you've already created.
      Whenever this parameter will be ignored except in that case.
    Type: String
    Default: your-app-example.com.


# Mappings:

Conditions:
  createRoute53NewHostedZone:
    Fn::Or:
      - !Equals [ !Ref Route53CreatingMode, "CreateNewIndependentHostedZone" ]
      - !Equals [ !Ref Route53CreatingMode, "CreateNewDependentSubDomainHostedZone" ]
  createNewDependentSubDomainHostedZone: !Equals [ !Ref Route53CreatingMode, "CreateNewDependentSubDomainHostedZone" ]
  dependsOnExistingHostedZone: !Equals [ !Ref Route53CreatingMode, "DependOnExistingHostedZone" ]

# ------------------------------------------------------------
# Resources section
# ------------------------------------------------------------
Resources:
  # ----------------------------------------
  # Route53 HostedZone and NS Delegation Records
  # ----------------------------------------

  # AWS::Route53::HostedZone
  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-route53-hostedzone.html
  Route53HostedZone:
    Type: "AWS::Route53::HostedZone"
    Condition: createRoute53NewHostedZone
    Properties:
      Name:
        Fn::If:
          - createNewDependentSubDomainHostedZone
          - !Sub ${EnvName}.${Route53ParentHostedZoneName}
          - !Sub ${Route53NewHostedZoneName}
      HostedZoneTags:
        - Key: Name
          Value: !Sub ${EnvName}-Route53HostedZone
        - Key: Env
          Value: !Ref EnvName
        - Key: AppService
          Value: !Ref AppServiceName

  # AWS::Route53::RecordSet
  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-recordset.html
  Route53DelegationInParent:
    Type: "AWS::Route53::RecordSet"
    Condition: createNewDependentSubDomainHostedZone
    Properties:
      HostedZoneId: !Ref "Route53ParentHostedZoneId"
      Name: !Sub ${EnvName}.${Route53ParentHostedZoneName}
      Type: NS
      ResourceRecords:
        !GetAtt Route53HostedZone.NameServers
      TTL: "172800"

# ------------------------------------------------------------
# Outputs section
# ------------------------------------------------------------
Outputs:
  Route53HostedZoneId:
    Description: "Route53 Hosted Zone Id."
    Value:
      Fn::If:
        - dependsOnExistingHostedZone
        - !Ref Route53DependentHostedZoneId
        - !Ref Route53HostedZone
    Export:
      Name: !Sub ${EnvName}-Route53HostedZoneId

  Route53HostedZoneName:
    Description: "Route53 Hosted Zone Name."
    Value:
      Fn::If:
        - dependsOnExistingHostedZone
        - !Ref Route53DependentHostedZoneName
        - Fn::If:
          - createNewDependentSubDomainHostedZone
          - !Sub ${EnvName}.${Route53ParentHostedZoneName}
          - !Sub ${Route53NewHostedZoneName}
    Export:
      Name: !Sub ${EnvName}-Route53HostedZoneName

