Description:
  This template creates an ACM instance.
  This template depends on the following export names.

  "${EnvName}-ACMDomainName"


# ------------------------------------------------------------
# Parameters section
# ------------------------------------------------------------
Parameters:
  EnvName:
    Description: An environment name that will be prefixed to resource names
    Type: String
    Default: Dev1
    AllowedValues:
      - Dev1
      - Dev2
      - It1
      - It2
      - Prd

  ServiceName:
    Description: Please enter the service name provided to the customer
    Type: String
    Default: Amber

  RevisionNumber:
    Description: The revision number of this template consists of 3 parts.
    Type: String
    Default: 0.1.0

Conditions:
  isPrdEnv: !Equals [ !Ref EnvName, "Prd" ]
  NotCreateInPrd: !Not [!Equals [ !Ref EnvName, "Prd" ]]


# ------------------------------------------------------------
# Resources section
# ------------------------------------------------------------
Resources:

  # ----------------------------------------
  # ACM Certificate
  # ----------------------------------------
  ACMCert:
    Type: "AWS::CertificateManager::Certificate"
    Properties: 
      DomainName:
        Fn::ImportValue: !Sub ${EnvName}-ACMDomainName
      SubjectAlternativeNames:
        - Fn::Join:
          - ""
          - - "*."
            - Fn::ImportValue: !Sub ${EnvName}-ACMDomainName
      Tags:
        - Key: Name
          Value:
            Fn::ImportValue: !Sub ${EnvName}-ACMDomainName
        - Key: Env
          Value: !Ref EnvName
        - Key: Service
          Value: !Ref ServiceName

# ------------------------------------------------------------
# Outputs section
# ------------------------------------------------------------
Outputs:
  ACMCertArn:
    Description: "ACM ARN"
    Value: !Ref ACMCert
    Export:
      Name: !Sub ${EnvName}-ACMCertArn


