AWSTemplateFormatVersion: '2010-09-09'
Description: >
  This template is intended to be used for CloudFormation StackSets.
  That enables you to create fundamental IAM roles into each target AWS accounts.
  Those are used for AssumeRole by IAM users in your master AWS account.

  Please notice this template requires the "CAPABILITY_NAMED_IAM" capability to create a CloudFormation stack.
  In addition, since this template creates an IAM Role with fixed name, I recommend you to create a CFn stack in the N.Virginia(us-east-1) region.

  A sample command line with necessary parameters is below.
  $ aws cloudformation create-stack-set --region us-east-1 --stack-name <stack name> \
  --template-body file://<this file name> \
  --parameters ParameterKey=AdministratorAwsAccountId,ParameterValue=123456789012 \
  --capabilities CAPABILITY_NAMED_IAM \


# ------------------------------------------------------------
# Parameters section
# ------------------------------------------------------------
Parameters:
  AdministratorAwsAccountId:
    Description:
      An AWS account id where all IAM users created in and they will be principals placed into each Role's trust relationship policy.
    Type: Number
    Default: 123456789012
  FullAdministratorRoleName:
    Description:
      The IAM Role name of Full Administrators.
    Type: String
    Default:
      FullAdministratorRole
  AccountingRoleName:
    Description:
      The IAM Role name of Accountants.
    Type: String
    Default:
      AccountingRole


# ------------------------------------------------------------
# Resources section
# ------------------------------------------------------------
Resources:
  # AWS::IAM::Role - AWS CloudFormation
  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-role.html
  FullAdministratorRole:
    Type: AWS::IAM::Role
    Properties: 
      RoleName: !Ref FullAdministratorRoleName
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              AWS:
                - !Ref AdministratorAwsAccountId
            Action:
              - sts:AssumeRole
      Description:
        This role allows IAM users in the administrator account to perform AssumeRole to obtain the privileges of this AWS account
      Path: '/'
      Policies: 
        - PolicyName: AllowAdministratorAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action: "*"
                Resource: "*"
      Tags: 
        - Key: Name
          Value: !Ref FullAdministratorRoleName
        - Key: EnvName
          Value: All

  # AWS::IAM::Role - AWS CloudFormation
  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-role.html
  AccountingRole:
    Type: AWS::IAM::Role
    Properties: 
      RoleName: !Ref AccountingRoleName
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              AWS:
                - !Ref AdministratorAwsAccountId
            Action:
              - sts:AssumeRole
      Description:
        This role allows IAM users in the administrator account to invoke billing-related actions within the target AWS account.
      Path: '/'
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/job-function/Billing
      Tags: 
        - Key: Name
          Value: !Ref AccountingRoleName
        - Key: EnvName
          Value: All


